var treatmentplant = [{
    "type": "FeatureCollection",
    "name": "wwtpScot",
    "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
    "features": [
        { "type": "Feature", "properties": { "WWTP_NAME": "ABERFELDY WWTP", "POP_SERVED": 4062 }, "geometry": { "type": "Point", "coordinates": [-3.859, 56.624] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "ABOYNE WWTP", "POP_SERVED": 3315 }, "geometry": { "type": "Point", "coordinates": [-2.752, 57.072] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "ALFORD WWTP", "POP_SERVED": 2779 }, "geometry": { "type": "Point", "coordinates": [-2.678, 57.243] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "ALLANFEARN WWTP INVERNESS", "POP_SERVED": 80227 }, "geometry": { "type": "Point", "coordinates": [-4.15, 57.526] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "ALLERS STW", "POP_SERVED": 40923 }, "geometry": { "type": "Point", "coordinates": [-4.08, 55.797] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "ALLOA WWTW", "POP_SERVED": 45455 }, "geometry": { "type": "Point", "coordinates": [-3.793, 56.105] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "ALVA WWTW", "POP_SERVED": 6977 }, "geometry": { "type": "Point", "coordinates": [-3.818, 56.147] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "ALYTH WWTP", "POP_SERVED": 2832 }, "geometry": { "type": "Point", "coordinates": [-3.212, 56.622] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "ANNAN KENzIELS STW", "POP_SERVED": 13145 }, "geometry": { "type": "Point", "coordinates": [-3.264, 54.968] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "ANNANDALE WATER MSA STW", "POP_SERVED": 2000 }, "geometry": { "type": "Point", "coordinates": [-3.408, 55.219] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "ARDOCH STW", "POP_SERVED": 65631 }, "geometry": { "type": "Point", "coordinates": [-4.611, 55.938] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "ARMADALE WWTW", "POP_SERVED": 12674 }, "geometry": { "type": "Point", "coordinates": [-3.701, 55.907] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "AUCHTERARDER WWTP", "POP_SERVED": 4721 }, "geometry": { "type": "Point", "coordinates": [-3.656, 56.336] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "AVIEMORE STW", "POP_SERVED": 5887 }, "geometry": { "type": "Point", "coordinates": [-3.815, 57.194] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "BALFRON WWTW", "POP_SERVED": 1783 }, "geometry": { "type": "Point", "coordinates": [-4.333, 56.065] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "BALLATER STW", "POP_SERVED": 4388 }, "geometry": { "type": "Point", "coordinates": [-3.024, 57.056] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "BANFF MACDUFF WWTW   MORAY PFI", "POP_SERVED": 12133 }, "geometry": { "type": "Point", "coordinates": [-2.474, 57.675] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "BATHGATE WWTW", "POP_SERVED": 14838 }, "geometry": { "type": "Point", "coordinates": [-3.663, 55.917] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "BIGGAR STW", "POP_SERVED": 3011 }, "geometry": { "type": "Point", "coordinates": [-3.563, 55.612] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "BLACKBURN WWTW", "POP_SERVED": 22771 }, "geometry": { "type": "Point", "coordinates": [-3.589, 55.872] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "BLACKWOOD STW", "POP_SERVED": 4042 }, "geometry": { "type": "Point", "coordinates": [-3.903, 55.668] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "BLAIR ATHOLL WWTP", "POP_SERVED": 554 }, "geometry": { "type": "Point", "coordinates": [-3.833, 56.759] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "BLAIRGOWRIE WWTP", "POP_SERVED": 9996 }, "geometry": { "type": "Point", "coordinates": [-3.315, 56.586] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "BO NESS WWTW", "POP_SERVED": 16168 }, "geometry": { "type": "Point", "coordinates": [-3.561, 56.022] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "BONNYBRIDGE WWTW", "POP_SERVED": 14966 }, "geometry": { "type": "Point", "coordinates": [-3.855, 56.012] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "BOTHWELLBANK STW", "POP_SERVED": 25108 }, "geometry": { "type": "Point", "coordinates": [-4.082, 55.798] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "BOWHOUSE WWTW", "POP_SERVED": 5514 }, "geometry": { "type": "Point", "coordinates": [-3.172, 56.27] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "BRECHIN WWTP", "POP_SERVED": 10399 }, "geometry": { "type": "Point", "coordinates": [-2.622, 56.721] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "CALDERCRUIX STW", "POP_SERVED": 0 }, "geometry": { "type": "Point", "coordinates": [-3.908, 55.888] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "CALLANDER WWTW", "POP_SERVED": 4157 }, "geometry": { "type": "Point", "coordinates": [-4.199, 56.236] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "CARBARNS STW", "POP_SERVED": 47915 }, "geometry": { "type": "Point", "coordinates": [-3.967, 55.761] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "CARSTAIRS JUNCTION STW", "POP_SERVED": 2945 }, "geometry": { "type": "Point", "coordinates": [-3.659, 55.683] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "CATRINEHOLM STW", "POP_SERVED": 2421 }, "geometry": { "type": "Point", "coordinates": [-4.344, 55.503] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "COMRIE WWTP", "POP_SERVED": 2273 }, "geometry": { "type": "Point", "coordinates": [-3.963, 56.371] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "CONON BRIDGE WWTP", "POP_SERVED": 2474 }, "geometry": { "type": "Point", "coordinates": [-4.425, 57.573] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "CORPACH WWTW", "POP_SERVED": 1532 }, "geometry": { "type": "Point", "coordinates": [-5.135, 56.841] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "COUPAR ANGUS WWTP", "POP_SERVED": 10250 }, "geometry": { "type": "Point", "coordinates": [-3.28, 56.549] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "COURSINGTON STW", "POP_SERVED": 7466 }, "geometry": { "type": "Point", "coordinates": [-3.986, 55.798] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "COWIE WWTW STIRLING", "POP_SERVED": 8898 }, "geometry": { "type": "Point", "coordinates": [-3.832, 56.101] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "COYLTON STW", "POP_SERVED": 2700 }, "geometry": { "type": "Point", "coordinates": [-4.532, 55.448] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "CRIEFF WWTP", "POP_SERVED": 9336 }, "geometry": { "type": "Point", "coordinates": [-3.84, 56.359] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "CUPAR WWTW", "POP_SERVED": 14780 }, "geometry": { "type": "Point", "coordinates": [-2.99, 56.322] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "DALBEATTIE STW", "POP_SERVED": 4820 }, "geometry": { "type": "Point", "coordinates": [-3.824, 54.921] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "DALDERSE WWTW", "POP_SERVED": 92954 }, "geometry": { "type": "Point", "coordinates": [-3.759, 56.021] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "DALDOWIE STW", "POP_SERVED": 269679 }, "geometry": { "type": "Point", "coordinates": [-4.127, 55.832] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "DALMARNOCK STW", "POP_SERVED": 231125 }, "geometry": { "type": "Point", "coordinates": [-4.216, 55.835] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "DALMELLINGTON STW", "POP_SERVED": 3564 }, "geometry": { "type": "Point", "coordinates": [-4.412, 55.326] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "DALMUIR PFI   DALMUIR WWTW", "POP_SERVED": 544390 }, "geometry": { "type": "Point", "coordinates": [-4.444, 55.908] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "DALSCONE STW new", "POP_SERVED": 3804 }, "geometry": { "type": "Point", "coordinates": [-3.6, 55.087] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "DALSCONE STW  old", "POP_SERVED": 2433 }, "geometry": { "type": "Point", "coordinates": [-3.6, 55.087] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "DENNY WWTW", "POP_SERVED": 11676 }, "geometry": { "type": "Point", "coordinates": [-3.891, 56.024] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "DINGWALL WWTP", "POP_SERVED": 7549 }, "geometry": { "type": "Point", "coordinates": [-4.41, 57.593] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "DOLLAR WWTW", "POP_SERVED": 2763 }, "geometry": { "type": "Point", "coordinates": [-3.69, 56.159] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "DORNOCH WWTP", "POP_SERVED": 2893 }, "geometry": { "type": "Point", "coordinates": [-4.032, 57.867] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "DOUGLAS STW", "POP_SERVED": 1808 }, "geometry": { "type": "Point", "coordinates": [-3.849, 55.562] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "DRONGAN STW", "POP_SERVED": 4401 }, "geometry": { "type": "Point", "coordinates": [-4.487, 55.436] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "DUNBLANE WWTW", "POP_SERVED": 9568 }, "geometry": { "type": "Point", "coordinates": [-3.963, 56.181] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "DUNFERMLINE STW", "POP_SERVED": 77678 }, "geometry": { "type": "Point", "coordinates": [-3.4, 56.005] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "DUNNSWOOD STW", "POP_SERVED": 31858 }, "geometry": { "type": "Point", "coordinates": [-3.953, 55.973] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "DUNOON WwTW", "POP_SERVED": 11014 }, "geometry": { "type": "Point", "coordinates": [-4.935, 55.928] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "DUNS WWTW", "POP_SERVED": 6691 }, "geometry": { "type": "Point", "coordinates": [-2.281, 55.77] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "EAGLESHAM  STW", "POP_SERVED": 3532 }, "geometry": { "type": "Point", "coordinates": [-4.263, 55.752] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "EAST CALDER WWTW", "POP_SERVED": 111668 }, "geometry": { "type": "Point", "coordinates": [-3.469, 55.899] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "EASTRIGGS STW", "POP_SERVED": 1880 }, "geometry": { "type": "Point", "coordinates": [-3.185, 54.971] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "EDINBURGH SEAFIELD WWTW", "POP_SERVED": 746604 }, "geometry": { "type": "Point", "coordinates": [-3.131, 55.996] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "ELLON WWTP", "POP_SERVED": 11196 }, "geometry": { "type": "Point", "coordinates": [-2.057, 57.364] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "ERSKINE STW", "POP_SERVED": 79004 }, "geometry": { "type": "Point", "coordinates": [-4.411, 55.897] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "EVANTON WWTP", "POP_SERVED": 1985 }, "geometry": { "type": "Point", "coordinates": [-4.326, 57.661] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "EYEMOUTH WWTW", "POP_SERVED": 0 }, "geometry": { "type": "Point", "coordinates": [-2.08, 55.879] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "FALLIN WWTW", "POP_SERVED": 2668 }, "geometry": { "type": "Point", "coordinates": [-3.873, 56.109] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "FAULDHOUSE WWTW", "POP_SERVED": 5323 }, "geometry": { "type": "Point", "coordinates": [-3.692, 55.824] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "FOCHABERS WWTP", "POP_SERVED": 3068 }, "geometry": { "type": "Point", "coordinates": [-3.101, 57.624] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "FORFAR NEW WWTP", "POP_SERVED": 20590 }, "geometry": { "type": "Point", "coordinates": [-2.912, 56.642] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "FORRES WWTP", "POP_SERVED": 15182 }, "geometry": { "type": "Point", "coordinates": [-3.602, 57.629] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "FORT WILLIAM NEW WWTP", "POP_SERVED": 14695 }, "geometry": { "type": "Point", "coordinates": [-5.113, 56.828] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "FORTH STW", "POP_SERVED": 2353 }, "geometry": { "type": "Point", "coordinates": [-3.677, 55.76] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "FRASERBURGH WWTW  ABERDEEN PFI", "POP_SERVED": 27379 }, "geometry": { "type": "Point", "coordinates": [-2.042, 57.698] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "GALASHIELS WWTW", "POP_SERVED": 28145 }, "geometry": { "type": "Point", "coordinates": [-2.771, 55.608] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "GIRVAN STW", "POP_SERVED": 13851 }, "geometry": { "type": "Point", "coordinates": [-4.867, 55.261] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "GLENEAGLES STW", "POP_SERVED": 3500 }, "geometry": { "type": "Point", "coordinates": [-3.699, 56.292] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "GOREBRIDGE WWTW", "POP_SERVED": 3821 }, "geometry": { "type": "Point", "coordinates": [-3.055, 55.84] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "GRANTOWN ON SPEY WWTP", "POP_SERVED": 3769 }, "geometry": { "type": "Point", "coordinates": [-3.612, 57.32] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "GRETNA STW", "POP_SERVED": 5048 }, "geometry": { "type": "Point", "coordinates": [-3.08, 54.986] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "GUARDBRIDGE WWTW", "POP_SERVED": 4576 }, "geometry": { "type": "Point", "coordinates": [-2.886, 56.365] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "HADDINGTON WWTW", "POP_SERVED": 11985 }, "geometry": { "type": "Point", "coordinates": [-2.751, 55.962] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "HAMILTON STW", "POP_SERVED": 62664 }, "geometry": { "type": "Point", "coordinates": [-4.055, 55.796] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "HAWICK WWTW", "POP_SERVED": 17551 }, "geometry": { "type": "Point", "coordinates": [-2.765, 55.431] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "HELENSBURGH   STW", "POP_SERVED": 13465 }, "geometry": { "type": "Point", "coordinates": [-4.717, 55.98] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "HUNTLY WWTW", "POP_SERVED": 6301 }, "geometry": { "type": "Point", "coordinates": [-2.775, 57.452] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "INSCH   WWTP", "POP_SERVED": 2715 }, "geometry": { "type": "Point", "coordinates": [-2.598, 57.342] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "INVERCLYDE WWT SERVICE", "POP_SERVED": 91453 }, "geometry": { "type": "Point", "coordinates": [-4.895, 55.937] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "INVERURIE NEW WWTP", "POP_SERVED": 24086 }, "geometry": { "type": "Point", "coordinates": [-2.363, 57.27] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "INVERURIE WWTP", "POP_SERVED": 0 }, "geometry": { "type": "Point", "coordinates": [-2.368, 57.274] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "IRON MILL BAY WWTW", "POP_SERVED": 19116 }, "geometry": { "type": "Point", "coordinates": [-3.518, 56.035] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "JEDBURGH WWTW", "POP_SERVED": 4719 }, "geometry": { "type": "Point", "coordinates": [-2.536, 55.515] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "KEITH WWTP", "POP_SERVED": 6194 }, "geometry": { "type": "Point", "coordinates": [-2.944, 57.554] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "KELSO WWTW", "POP_SERVED": 8242 }, "geometry": { "type": "Point", "coordinates": [-2.416, 55.604] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "KEMNAY WWTP", "POP_SERVED": 3938 }, "geometry": { "type": "Point", "coordinates": [-2.446, 57.245] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "KINCARDINE WWTW", "POP_SERVED": 3040 }, "geometry": { "type": "Point", "coordinates": [-3.721, 56.064] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "KINGUSSIE WWTP", "POP_SERVED": 1989 }, "geometry": { "type": "Point", "coordinates": [-4.042, 57.078] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "Kinneil Kerse", "POP_SERVED": 54927 }, "geometry": { "type": "Point", "coordinates": [-3.665, 56.014] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "KINROSS WWTW", "POP_SERVED": 5534 }, "geometry": { "type": "Point", "coordinates": [-3.41, 56.212] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "KIRKCALDY WWTW", "POP_SERVED": 61238 }, "geometry": { "type": "Point", "coordinates": [-3.138, 56.112] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "KIRKCONNEL STW", "POP_SERVED": 3684 }, "geometry": { "type": "Point", "coordinates": [-3.976, 55.381] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "KIRKWALL HEAD OF WORK WWTP", "POP_SERVED": 12852 }, "geometry": { "type": "Point", "coordinates": [-2.909, 59.013] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "KIRRIEMUIR WWTP", "POP_SERVED": 7272 }, "geometry": { "type": "Point", "coordinates": [-3.001, 56.659] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "LAIGHPARK   STW", "POP_SERVED": 130515 }, "geometry": { "type": "Point", "coordinates": [-4.422, 55.865] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "LANARK STW", "POP_SERVED": 12409 }, "geometry": { "type": "Point", "coordinates": [-3.798, 55.674] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "LANGHOLM STW", "POP_SERVED": 2880 }, "geometry": { "type": "Point", "coordinates": [-2.993, 55.145] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "LARGS STW", "POP_SERVED": 14033 }, "geometry": { "type": "Point", "coordinates": [-4.893, 55.82] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "LAURENCEKIRK WWTP", "POP_SERVED": 4063 }, "geometry": { "type": "Point", "coordinates": [-2.521, 56.782] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "LESMAHAGOW STW", "POP_SERVED": 7713 }, "geometry": { "type": "Point", "coordinates": [-3.883, 55.648] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "LEVEN VALLEY LEVENMOUTH WWTW", "POP_SERVED": 194827 }, "geometry": { "type": "Point", "coordinates": [-2.986, 56.181] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "LINCLUDEN STW", "POP_SERVED": 8280 }, "geometry": { "type": "Point", "coordinates": [-3.625, 55.087] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "LINLITHGOW WWTW", "POP_SERVED": 13951 }, "geometry": { "type": "Point", "coordinates": [-3.627, 55.985] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "LIVINGSTON WWTW", "POP_SERVED": 8083 }, "geometry": { "type": "Point", "coordinates": [-3.559, 55.883] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "LOCHMABEN STW", "POP_SERVED": 1977 }, "geometry": { "type": "Point", "coordinates": [-3.403, 55.119] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "LOCHWINNOCH STW", "POP_SERVED": 2640 }, "geometry": { "type": "Point", "coordinates": [-4.62, 55.795] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "LOCKERBIE STW", "POP_SERVED": 5861 }, "geometry": { "type": "Point", "coordinates": [-3.403, 55.119] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "MAUCHLINE STW", "POP_SERVED": 4389 }, "geometry": { "type": "Point", "coordinates": [-4.391, 55.499] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "MAULDSLIE   STW", "POP_SERVED": 18626 }, "geometry": { "type": "Point", "coordinates": [-3.905, 55.734] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "MAYBOLE STW", "POP_SERVED": 4955 }, "geometry": { "type": "Point", "coordinates": [-4.652, 55.341] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "MEADOWHEAD WWT SERVICE", "POP_SERVED": 334998 }, "geometry": { "type": "Point", "coordinates": [-4.693, 55.583] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "MELROSE WWTW", "POP_SERVED": 3767 }, "geometry": { "type": "Point", "coordinates": [-2.715, 55.603] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "MINTLAW WWTP", "POP_SERVED": 3081 }, "geometry": { "type": "Point", "coordinates": [-1.998, 57.513] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "MOFFAT STW", "POP_SERVED": 3270 }, "geometry": { "type": "Point", "coordinates": [-3.436, 55.323] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "MONTROSE WWTP", "POP_SERVED": 18019 }, "geometry": { "type": "Point", "coordinates": [-2.458, 56.703] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "MORAY EAST WWTW MORAY PFI", "POP_SERVED": 23586 }, "geometry": { "type": "Point", "coordinates": [-2.93, 57.696] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "MORAY WEST LOSSIEMOUTH  STW", "POP_SERVED": 42949 }, "geometry": { "type": "Point", "coordinates": [-3.265, 57.729] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "MUIR OF ORD NEW STW", "POP_SERVED": 4343 }, "geometry": { "type": "Point", "coordinates": [-4.415, 57.503] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "NAIRN WWTP", "POP_SERVED": 12672 }, "geometry": { "type": "Point", "coordinates": [-3.854, 57.601] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "NEILSTON STW", "POP_SERVED": 5903 }, "geometry": { "type": "Point", "coordinates": [-4.427, 55.789] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "NEW CUMNOCK STW", "POP_SERVED": 3723 }, "geometry": { "type": "Point", "coordinates": [-4.176, 55.401] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "NEWBRIDGE WWTW", "POP_SERVED": 28534 }, "geometry": { "type": "Point", "coordinates": [-3.395, 55.949] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "NEWBURGH WWTW", "POP_SERVED": 2381 }, "geometry": { "type": "Point", "coordinates": [-3.227, 56.357] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "NEWMACHAR WWTP", "POP_SERVED": 3117 }, "geometry": { "type": "Point", "coordinates": [-2.187, 57.244] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "NEWTON STEWART STW", "POP_SERVED": 5020 }, "geometry": { "type": "Point", "coordinates": [-4.454, 54.946] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "NEWTOWN ST BOSWELL WWTW", "POP_SERVED": 1994 }, "geometry": { "type": "Point", "coordinates": [-2.665, 55.578] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "NIGG WWTW  ABERDEEN PFI", "POP_SERVED": 278900 }, "geometry": { "type": "Point", "coordinates": [-2.025, 57.128] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "OBAN STW", "POP_SERVED": 13228 }, "geometry": { "type": "Point", "coordinates": [-5.485, 56.421] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "OLDMELDRUM WWTP", "POP_SERVED": 3252 }, "geometry": { "type": "Point", "coordinates": [-2.356, 57.333] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "ORMISTON WWTW", "POP_SERVED": 3144 }, "geometry": { "type": "Point", "coordinates": [-2.925, 55.911] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "PATNA STW", "POP_SERVED": 2242 }, "geometry": { "type": "Point", "coordinates": [-4.506, 55.379] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "PEEBLES WWTW", "POP_SERVED": 10501 }, "geometry": { "type": "Point", "coordinates": [-3.16, 55.646] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "PENICUIK WWTW", "POP_SERVED": 12685 }, "geometry": { "type": "Point", "coordinates": [-3.203, 55.837] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "PERSLEY WWTP", "POP_SERVED": 48738 }, "geometry": { "type": "Point", "coordinates": [-2.157, 57.177] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "PERTH CITY WWTP", "POP_SERVED": 83915 }, "geometry": { "type": "Point", "coordinates": [-3.38, 56.384] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "PETERHEAD BURNHAVEN WWTP", "POP_SERVED": 32047 }, "geometry": { "type": "Point", "coordinates": [-1.784, 57.484] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "PHILIPSHILL STW", "POP_SERVED": 60996 }, "geometry": { "type": "Point", "coordinates": [-4.08, 55.797] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "PITLOCHRY WWTP", "POP_SERVED": 5436 }, "geometry": { "type": "Point", "coordinates": [-3.723, 56.697] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "PLAINS STW", "POP_SERVED": 5365 }, "geometry": { "type": "Point", "coordinates": [-3.929, 55.874] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "ROVAHEAD WWTW LERWICK", "POP_SERVED": 25629 }, "geometry": { "type": "Point", "coordinates": [-1.14, 60.191] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "SANQUHAR STW", "POP_SERVED": 2135 }, "geometry": { "type": "Point", "coordinates": [-3.924, 55.359] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "SCONE WWTP", "POP_SERVED": 4972 }, "geometry": { "type": "Point", "coordinates": [-3.433, 56.411] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "SELKIRK WWTW", "POP_SERVED": 7202 }, "geometry": { "type": "Point", "coordinates": [-2.835, 55.561] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "SHIELDHALL STW", "POP_SERVED": 533800 }, "geometry": { "type": "Point", "coordinates": [-4.34, 55.869] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "SHOTTS STW", "POP_SERVED": 9684 }, "geometry": { "type": "Point", "coordinates": [-3.811, 55.812] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "SKELLYTON STW", "POP_SERVED": 16223 }, "geometry": { "type": "Point", "coordinates": [-3.952, 55.752] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "SOUTH QUEENSFERRY WWTW", "POP_SERVED": 8590 }, "geometry": { "type": "Point", "coordinates": [-3.415, 56.0] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "SOUTHERNESS STW", "POP_SERVED": 3227 }, "geometry": { "type": "Point", "coordinates": [-3.582, 54.881] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "SPRINGFIELD WWTW", "POP_SERVED": 6995 }, "geometry": { "type": "Point", "coordinates": [-3.053, 56.293] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "ST ANDREWS WWTW", "POP_SERVED": 19407 }, "geometry": { "type": "Point", "coordinates": [-2.753, 56.336] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "STEVENSTON WWTSERVICE", "POP_SERVED": 84792 }, "geometry": { "type": "Point", "coordinates": [-4.754, 55.616] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "STEWARTON STW", "POP_SERVED": 7242 }, "geometry": { "type": "Point", "coordinates": [-4.534, 55.671] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "STIRLING WWTW", "POP_SERVED": 73019 }, "geometry": { "type": "Point", "coordinates": [-3.918, 56.12] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "STONEHOUSE STW", "POP_SERVED": 5289 }, "geometry": { "type": "Point", "coordinates": [-3.967, 55.702] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "STORNOWAY HOLM WWTP", "POP_SERVED": 12426 }, "geometry": { "type": "Point", "coordinates": [-6.335, 58.187] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "STRANRAER PORT RODIE STW", "POP_SERVED": 0 }, "geometry": { "type": "Point", "coordinates": [-5.031, 54.91] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "STRATHAVEN STW", "POP_SERVED": 7662 }, "geometry": { "type": "Point", "coordinates": [-4.042, 55.675] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "STRATHPEFFER WWTP", "POP_SERVED": 1537 }, "geometry": { "type": "Point", "coordinates": [-4.523, 57.593] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "SWINSTIE STW", "POP_SERVED": 11458 }, "geometry": { "type": "Point", "coordinates": [-3.905, 55.796] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "TAIN WWTP", "POP_SERVED": 4823 }, "geometry": { "type": "Point", "coordinates": [-4.05, 57.818] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "TAY PFI   HATTON WWTW", "POP_SERVED": 239892 }, "geometry": { "type": "Point", "coordinates": [-2.629, 56.514] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "THURSO STW", "POP_SERVED": 9700 }, "geometry": { "type": "Point", "coordinates": [-3.496, 58.609] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "TILLICOULTRY WWTW", "POP_SERVED": 6617 }, "geometry": { "type": "Point", "coordinates": [-3.746, 56.147] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "TROQUEER STW", "POP_SERVED": 44031 }, "geometry": { "type": "Point", "coordinates": [-3.612, 55.053] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "TURRIFF WWTP", "POP_SERVED": 7594 }, "geometry": { "type": "Point", "coordinates": [-2.477, 57.541] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "UNDERWOOD   STW", "POP_SERVED": 21393 }, "geometry": { "type": "Point", "coordinates": [-4.285, 55.458] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "VALLEYFIELD WWTW", "POP_SERVED": 8666 }, "geometry": { "type": "Point", "coordinates": [-3.598, 56.046] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "WALKERBURN WWTW", "POP_SERVED": 4452 }, "geometry": { "type": "Point", "coordinates": [-2.998, 55.626] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "WHITBURN   WWTW", "POP_SERVED": 12568 }, "geometry": { "type": "Point", "coordinates": [-3.679, 55.871] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "WICK WWTW", "POP_SERVED": 8607 }, "geometry": { "type": "Point", "coordinates": [-3.057, 58.441] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "WINCHBURGH WWTW", "POP_SERVED": 2862 }, "geometry": { "type": "Point", "coordinates": [-3.455, 55.954] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "AVOCH WWTW", "POP_SERVED": 1455 }, "geometry": { "type": "Point", "coordinates": [-4.176, 57.552] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "BANCHORY STW", "POP_SERVED": 8503 }, "geometry": { "type": "Point", "coordinates": [-2.476, 57.054] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "BLACKFORD WWTW", "POP_SERVED": 1483 }, "geometry": { "type": "Point", "coordinates": [-3.786, 56.263] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "DRUMNADROCHIT WWTP", "POP_SERVED": 1417 }, "geometry": { "type": "Point", "coordinates": [-4.463, 57.334] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "FASLANE STW", "POP_SERVED": 3500 }, "geometry": { "type": "Point", "coordinates": [-4.817, 56.062] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "HARTHILL STW", "POP_SERVED": 4040 }, "geometry": { "type": "Point", "coordinates": [-3.747, 55.865] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "KILLEARN WASTE WATER TREATMENT WORKS", "POP_SERVED": 1607 }, "geometry": { "type": "Point", "coordinates": [-4.385, 56.026] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "LETHAM WTP", "POP_SERVED": 1653 }, "geometry": { "type": "Point", "coordinates": [-2.754, 56.629] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "MILNATHORT WASTE WATER TREATMENT WORKS", "POP_SERVED": 1923 }, "geometry": { "type": "Point", "coordinates": [-3.406, 56.22] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "MUIRKIRK STW", "POP_SERVED": 1795 }, "geometry": { "type": "Point", "coordinates": [-4.098, 55.511] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "NEWPORT and TAYPORT STW NEW", "POP_SERVED": 8335 }, "geometry": { "type": "Point", "coordinates": [-2.915, 56.451] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "NEWTONMORE WWTP", "POP_SERVED": 1788 }, "geometry": { "type": "Point", "coordinates": [-4.101, 57.067] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "PLEAN WASTE WATER TREATMENT WORKS", "POP_SERVED": 1979 }, "geometry": { "type": "Point", "coordinates": [-3.859, 56.063] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "SLAMANNAN WASTE WATER TREATMENT WORKS", "POP_SERVED": 1574 }, "geometry": { "type": "Point", "coordinates": [-3.832, 55.943] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "SPEAN BRIDGE_ROYBRIDGE WwTW", "POP_SERVED": 1015 }, "geometry": { "type": "Point", "coordinates": [-4.901, 56.893] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "STRATHBLANE STW", "POP_SERVED": 1860 }, "geometry": { "type": "Point", "coordinates": [-4.332, 55.992] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "DUNBAR SOUTHSTW", "POP_SERVED": 24589 }, "geometry": { "type": "Point", "coordinates": [-2.569, 55.991] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "COLDSTREAM", "POP_SERVED": 2413 }, "geometry": { "type": "Point", "coordinates": [-2.22588, 55.6641] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "TYNDRUM", "POP_SERVED": 567 }, "geometry": { "type": "Point", "coordinates": [-4.684, 56.423] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "CASTLE DOUGLAS New STW", "POP_SERVED": 4949 }, "geometry": { "type": "Point", "coordinates": [-3.973, 54.92] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "ALNESS and INVERGORDON WWTW", "POP_SERVED": 5575 }, "geometry": { "type": "Point", "coordinates": [-4.198, 57.682] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "BLACKRIDGE WWTW", "POP_SERVED": 2161 }, "geometry": { "type": "Point", "coordinates": [-3.743, 55.891] } },
        { "type": "Feature", "properties": { "WWTP_NAME": "LOCH RYAN WWTW", "POP_SERVED": 12600 }, "geometry": { "type": "Point", "coordinates": [-5.171, 54.891] } }
    ]
}
];
